-- Откат миграции 000001

DROP TABLE IF EXISTS jwt_tokens CASCADE;
DROP TABLE IF EXISTS sms_attempts CASCADE;
DROP TABLE IF EXISTS push_notifications CASCADE;
DROP TABLE IF EXISTS ratings CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS slots CASCADE;
DROP TABLE IF EXISTS marshals CASCADE;
DROP TABLE IF EXISTS clients CASCADE;

DROP FUNCTION IF EXISTS update_updated_at_column CASCADE;